### ISSUE TITLE
Currency codes?

### ISSUE THREAD

**Issue by boranaf** [AndrewRPorter/yahoo-historical#13]

**Comment by boranaf** [comment]
Firstly thanks for a very useful library.

Can I please ask help regarding getting currency rate historical data, such as EURUSD. I just noticed a previous issue raised but not solved. Perhaps sharing this link of a similar library which made it work could help?

https://pypi.org/project/yahoo-finance/

**Comment by AndrewRPorter** [comment]
The project link that you shared is abandoned and no longer works. Yahoo Finance does not seem to offer an API for historical currency rates. Look at these two endpoints: https://finance.yahoo.com/quote/EURUSD=X?p=EURUSD=X&.tsrc=fin-srch & https://finance.yahoo.com/quote/AAPL?p=AAPL.

**Comment by boranaf** [comment]
Thanks for your prompt reply. Sorry didnt understand what you meant by look at these two end points? Charts appear normal to me...Is not possible to download historical currency rates?

**Comment by AndrewRPorter** [comment]
@boranaf notice how the **AAPL** endpoint has a tab for Historical Data: https://finance.yahoo.com/quote/AAPL/history?p=AAPL. The **EURUSD** endpoint does not.

**Comment by boranaf** [comment]
got it, thanks, have you tried the same on Google Finance?  any suggestions for this?

I found one alternative that gets data from "fred" but data doesnt seem to be as uptodate
https://github.com/mortada/fredapi
