### ISSUE TITLE
API is not working

### ISSUE THREAD

**Issue by jimmylai-hk** [AndrewRPorter/yahoo-historical#19]
from yahoo_historical import Fetcher

data = Fetcher("AAPL", [2007,1,1], [2017,1,1])
print(data.get_historical())

The above code return the following.

Empty DataFrame
Columns: [Forbidden]
Index: []

**Comment by blahem** [comment]
I noticed the same 10 mins ago. I don't know why it does that. I hope it'll be fixed soon.

blahem

**Comment by blahem** [comment]
I found the solution!
When sending a get request with requests.get() in Python, you should also provide a simple header containing a blank user agent.

*So this doesn't work:
url="https://query1.finance.yahoo.com/v7/finance/download/MSFT?period1=1625443200&period2=1625875200&interval=1d&events=history&includeAdjustedClose=true"
requests.get(url).text
'Forbidden'

*But this solves the problem:
headers = { 'User-Agent': ''}
url="https://query1.finance.yahoo.com/v7/finance/download/MSFT?period1=1625443200&period2=1625875200&interval=1d&events=history&includeAdjustedClose=true"
requests.get(url,headers=headers).text

Hope this helps you,
blahem

**Comment by AndrewRPorter** [comment]
Thank you both for the help. I merged in @blahem PR and published a new version. Upgrade yahoo_historical to see the changes: `python3 -m pip install --upgrade yahoo_historical`
