### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by GatorByte** [AndrewRPorter/yahoo-historical#3]
Tried installing with pip and then by running the running the python code directly.
In both cases I get a SyntaxError: on line 13 position 53 (pointing to "interval").
You perhaps have a naming conflict?

**Comment by AndrewRPorter** [comment]
@GatorByte I will look into this, which version of Python are you using?

**Comment by GatorByte** [comment]
I am using 2.7.13 from an Anaconda 4.4.0 (64-bit). Used the PIP in a conda environment. Separately tried running in a Wing IDE shell. same error.

**Comment by AndrewRPorter** [comment]
@GatorByte I should have fixed this can you uninstall and re-install the package to verify?

**Comment by GatorByte** [comment]
Verified your fix worked. Downloads data from yahoo exactly as your example. Thanks for the quick response and for the nice work.
