### ISSUE TITLE
Download to csv

### ISSUE THREAD

**Issue by Fulvioo** [AndrewRPorter/yahoo-historical#7]
Hi (yes I am quite new to Python...) - while your code works very well - when I try to download long time series to csv files I always get it truncated btween the first 30 and the last 30 records. Any intentions to implement a 'download' function into your code? /Suggestions? That will help. Thx

**Comment by AndrewRPorter** [comment]
This is not a feature that I plan on implementing.

**Comment by Fulvioo** [comment]
Thanks for the quick answer Andrew ... Well ...If you can provide some suggestions, that would help as weel. Thanks again
