### ISSUE TITLE
Getting null values in dataframe

### ISSUE THREAD

**Issue by pmatos** [AndrewRPorter/yahoo-historical#8]
Doing:
```python
data = Fetcher("ALV.F", [2016,9,27], [2017,9,27])
```

and getting:
```
           Date        Open        High         Low       Close   Adj Close  \
0    2016-09-26        null        null        null        null        null
```

**Comment by AndrewRPorter** [comment]
Yes, some tickers in foreign exchanges seem to be giving invalid data. I will have to look more into this but my intuition is that yahoo finance supplies bad historical data for such tickers.

**Comment by pmatos** [comment]
I keep seeing the same problem... very strange. Wish there was an easy way to contact yahoo about this.

**Comment by AndrewRPorter** [comment]
I am no longer able to reproduce this
